### PR TITLE
Update paint.lua

### PR DESCRIPTION
**Pull request by Marcin1503**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Note: all code that paints like this relies on the zoom level (i.e. _View_ → _Window Size_). At 1× it looks bad (just like the recently added “auto-screenshot on completed run” functionality). Perhaps we should document this, or force the setting programmatically?

**Comment by kylecoburn** [comment]
Looks cool, I will test this out soon.

**Comment by kylecoburn** [comment]
@mathiasbynens 2x is the standard since the emulator is cramped at 1x and going bigger doesn't afford much. It doesn't break anything, and I assume people are going to resize it anyway, but it might be nice to document the setup process in more detail outside the main readme.

**Comment by kylecoburn** [comment]
Please note I am amending this with d4233a7d768d4a7d9976d03d2f358a5d3b77ef99 (as well as taking the opportunity to clean up some of the existing code). @Marcin1503 I think the changes I've made could be insightful for you. Thanks for the PR.

**Pull request merged**
