### PR TITLE
PokeBot V2 maybe ? No Save Corruption added + more settings options

### PR DESCRIPTION
**Pull request by bouletmarc**
Can you please update it to my version, it's pretty almost the same in the lua's, have more settings options, no save corruption run, can use custom path, custom name (more than 1letter), etc.

-Marc

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Nice work! It would probably be more manageable to submit small patches (i.e. 1 pull request per change / new feature) rather than one big patch that changes _everything_. Are you open to that?

**Comment by bouletmarc** [comment]
i'm not to request 7,600 changes one by one-,-' I know it's look huge, but it's not, it's kinda the same as it's already in the lua's but with 1 more run and options through it, Also I couldn't only pull request to add the "No save corruption" run, since I added functions through other files which can cause issue if you just don't submit everything (such as Abra, teleport attack, etc). Otherwise if this can be accepted, it might be my only intance of a big "pull request". I was planning about adding other runs, such as "save corruption", etc and thoses pull would be only for the paths.lua and strategies.lua. 

If you are looking for changes. I made a "Readme_modified_files_list" which can lead you to changes I made.

**Comment by kylecoburn** [comment]
This is really cool Marc, congrats on getting it completing runs! As it stands though, this is too convoluted to integrate into the main bot directly. I'm going to think about it more, but for the time being, I believe the best option is to link to your fork from the main readme.

**Comment by kylecoburn** [comment]
I'm closing this with 6510c0d160fb69435d0f8760af260b685ad1ebd0 for now; let me know if you have any further suggestions. At this point I don't want to integrate other categories into this repo, because it will create dependencies on all the helper/utility modules that I won't be able to maintain/support myself.

**Comment by bouletmarc** [comment]
no I dont have other suggestions, I thought it would be a great idea to make it, and ask to add it, I tought it would being done, but no, well anyway i'm no more working on this since I heard that, I wanted you to add it because I didnt wanted to do update anytime, and what you say above its like "I will cant update it" well it took me 7days to create the bot, including learning Your base code, I dont think learning mine would be hard since its the same, reason over reason, I'm just sure you didnt even opened 1 files, well i'll not say more what I think really ... xDDD have fun ;)

**Pull request closed without merging**
