### PR TITLE
Remove extraneous space

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by kylecoburn** [comment]
These are intentional. Fyi, the bot's standard for messages sent with /me that do not directly continue from the name begin with two spaces and a capital letter at the start to distinguish.

Open to changing the "beat the game" message, but the purpose was to make the time easier to read (at least when looking at the console, where it originated).

**Comment by mathiasbynens** [comment]
> These are intentional. Fyi, the bot's standard for messages sent with /me that do not directly continue from the name begin with two spaces and a capital letter at the start to distinguish.

Thanks for the info. There’s only a single space here, though (`" "..prefix`) – should I make it two then?

**Comment by kylecoburn** [comment]
The "/me " is added to all outgoing messages from the bot. Note that Twitch does not accept the format "/memessage", so that combines for two spaces.

**Comment by mathiasbynens** [comment]
Patch updated

**Comment by kylecoburn** [comment]
Thanks!

**Pull request merged**
