### PR TITLE
Update README for the new PB!

### PR DESCRIPTION
**Pull request by csuhta**
[Congrats](https://www.youtube.com/watch?v=lVE_ksd4WJw)! 🎉📣

### CODE REVIEW

**Comment by mathiasbynens** [comment]
#24

**Comment by csuhta** [comment]
Welp, that was a duplicate.

**Comment by mathiasbynens** [comment]
Doesn’t matter, we can still party in here!  🎉📣:dance:

**Comment by kylecoburn** [comment]
💃💃

**Comment by csuhta** [comment]
partyhard

**Pull request closed without merging**
